/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoire;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static memoire.Exercises.list;

/**
 *
 * @author abdeljabbar
 */
public class User extends javax.swing.JFrame {

    PreparedStatement presta = null;
    ResultSet reset = null;
    Connection con = null;
    public User() {
        initComponents();
        con= ConnectionDB.OpenConnection();
        chargeDataList();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
         setLocationRelativeTo(this);
         setResizable(false);
        if(Login.id_user!=1)
        {
            AddUser.setEnabled(false);
            this.DeleteUser.setEnabled(false);
            ListUsers.setVisible(false);
            username.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        UpdateUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListUsers = new javax.swing.JList<>();
        DeleteUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        AddUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 145, 190));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 24), new java.awt.Color(141, 241, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setText("UserName:");

        UpdateUser.setBackground(new java.awt.Color(220, 220, 220));
        UpdateUser.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        UpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoire/1494998024_edit-user.png"))); // NOI18N
        UpdateUser.setText("Update");
        UpdateUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        ListUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListUsers);

        DeleteUser.setBackground(new java.awt.Color(220, 220, 220));
        DeleteUser.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        DeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoire/1494997935_list-remove-user.png"))); // NOI18N
        DeleteUser.setText("Delete");
        DeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoire/1494997591_user_accounts_config.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Password:");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        AddUser.setBackground(new java.awt.Color(220, 220, 220));
        AddUser.setFont(new java.awt.Font("SimSun-ExtB", 0, 24)); // NOI18N
        AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memoire/1494996809_list-add-user.png"))); // NOI18N
        AddUser.setText("Add");
        AddUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(UpdateUser)
                                        .addGap(6, 6, 6)
                                        .addComponent(AddUser)))))
                        .addGap(196, 196, 196))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
       
        try{
            
                   if(username.getText().length()==0 ||password.getText().length()==0)
                    {
                        JOptionPane.showMessageDialog(this," UserName or password is Empty");
                        return;
                    }
                    String qeuryselect = "select Count(*) from [DB_MEMIOR].[dbo].[User] where username = ?";
           
                            presta = con.prepareStatement(qeuryselect);
                            presta.setString(1,username.getText());
                            reset = presta.executeQuery();
                            
                                if (reset.next()) 
                                   {
                                       if( reset.getInt(1)==0)
                                       { 
                                           String query = "INSERT INTO [DB_MEMIOR].[dbo].[User] (username,password,Role)values (?,?,?)";
                                       
                                                presta = con.prepareStatement(query);
                                                presta.setString(1, username.getText());
                                                presta.setString(2, MD5(password.getText()));
                                                presta.setString(3,"User");
                                                presta.execute();
                                                chargeDataList();
                                       }
                                       else
                                       {
                                            JOptionPane.showMessageDialog(null, "Username is reserved");
                                       }
                                   }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() );
        }
    }//GEN-LAST:event_AddUserActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        try
        {
            /* String qeuryselect = "select Count(*) from [DB_MEMIOR].[dbo].[User] where username = ? and IdUser != ?";
           
                            presta = con.prepareStatement(qeuryselect);
                            presta.setString(1,username.getText());
                            presta.setInt(2,Login.id_user);
                            reset = presta.executeQuery();
                            
                                if (reset.next()) 
                                   {
                                       
                                       if( reset.getInt(1)==0)
            
                                       {*/
                            if(password.getText().length()==0)
                                {
                                    JOptionPane.showMessageDialog(this,"password is Empty");
                                    return;
                                }
                                            String query = "UPDATE [DB_MEMIOR].[dbo].[users] SET  password=? where  IdUser =?";
                                            presta = con.prepareStatement(query);
                                            presta.setString(1,MD5( password.getText()));
                                            presta.setInt(2,Login.id_user);
                                            presta.execute();
                                            chargeDataList();
                                            JOptionPane.showMessageDialog(null,"The UpDate process Was SuccessFul");
                                       /*}
                                       else
                                       {
                                            JOptionPane.showMessageDialog(null, "Username is reserved");
                                       }
                                   }*/
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void ListUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListUsersValueChanged
        username.setText(ListUsers.getSelectedValue());
        password.setText("0000000");
    }//GEN-LAST:event_ListUsersValueChanged

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // TODO add your handling code here:
        
           try
           {    if( ListUsers.isSelectionEmpty()==false)
                {
                    JOptionPane.showMessageDialog(null,"The Delete process Was NOT SuccessFul");
                    return;
                }
                String qeury = "Delete from [DB_MEMIOR].[dbo].[User] where username = ?";
                presta = con.prepareStatement(qeury);
                presta.setString(1,ListUsers.getSelectedValue());
                presta.execute();
                chargeDataList();
                JOptionPane.showMessageDialog(this, "The Delete process Was SuccessFul");
                
               
                
            }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(this, e.getMessage());
           }
    }//GEN-LAST:event_DeleteUserActionPerformed
public void chargeDataList()
{
     try
        {
             String qeury = "select * from [DB_MEMIOR].[dbo].[user] where Role ='User'";
           
                            presta = con.prepareStatement(qeury);
                           // presta.setString(1,nameM.getText());
                            reset = presta.executeQuery();
                            
        Vector<String> temp = new Vector<String>();
        while (reset.next())
        {
            temp.add(reset.getString("username"));
        }
        //Jlist acctList = new Jlist(temp);
        ListUsers.setListData(temp);
        
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
    public String MD5(String md5)
    {
    try {
        java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
        byte[] array = md.digest(md5.getBytes());
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < array.length; ++i)
        {
          sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1,3));
        }
        return sb.toString();
       } catch (java.security.NoSuchAlgorithmException e) 
        {
        }
    return null;
    }

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               // if ("Nimbus".equals(info.getName())) {
                   // javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   // break;
                //}
            //}
       // } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
           // java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new User().setVisible(true);
           // }
        //});
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JList<String> ListUsers;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
