/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoire;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import static memoire.Exercises.list;

/**
 *
 * @author abdeljabbar
 */
public class User extends javax.swing.JFrame {

    PreparedStatement presta = null;
    ResultSet reset = null;
    Connection con = null;
    public User() {
        initComponents();
        con= ConnectionDB.OpenConnection();
        chargeDataList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListUsers = new javax.swing.JList<>();
        username = new javax.swing.JTextField();
        AddUser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListUsers);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        AddUser.setText("Add");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        UpdateUser.setText("Update");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        DeleteUser.setText("Delete");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        jLabel1.setText("UserName:");

        jLabel2.setText("PassWord:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteUser)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(UpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(AddUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(password)
                        .addGap(35, 35, 35)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteUser)
                    .addComponent(UpdateUser)
                    .addComponent(AddUser))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
       
        try{
             String qeuryselect = "select Count(*) from [DB_MEMIOR].[dbo].[users] where username = ?";
           
                            presta = con.prepareStatement(qeuryselect);
                            presta.setString(1,username.getText());
                            reset = presta.executeQuery();
                            
                                if (reset.next()) 
                                   {
                                       if( reset.getInt(1)==0)
                                       { 
                                           String query = "INSERT INTO [DB_MEMIOR].[dbo].[users] (username,password)values (?,?)";
                                       
                                                presta = con.prepareStatement(query);
                                                presta.setString(1, username.getText());
                                                presta.setString(2, password.getText());
                                                presta.execute();
                                       }
                                       else
                                       {
                                            JOptionPane.showMessageDialog(null, "Username is reserved");
                                       }
                                   }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() );
        }
    }//GEN-LAST:event_AddUserActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        try
        {
             String qeuryselect = "select Count(*) from [DB_MEMIOR].[dbo].[users] where username = ?";
           
                            presta = con.prepareStatement(qeuryselect);
                            presta.setString(1,username.getText());
                            reset = presta.executeQuery();
                            
                                if (reset.next()) 
                                   {
                                       if( reset.getInt(1)==0)
                                       {
                                            String query = "UPDATE [DB_MEMIOR].[dbo].[users] SET username=?, password=? where  IdUser =?";
                                            presta = con.prepareStatement(query);
                                            presta.setString(1, username.getText());
                                            presta.setString(2, password.getText());
                                            presta.setInt(3, 1/*Login.id_user*/);
                                            presta.execute(); 
                                       }
                                       else
                                       {
                                            JOptionPane.showMessageDialog(null, "Username is reserved");
                                       }
                                   }
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void ListUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListUsersValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ListUsersValueChanged

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // TODO add your handling code here:
        
           try
           {    if( ListUsers.isSelectionEmpty()==false)
                {
                String qeury = "Delete from [DB_MEMIOR].[dbo].[users] where username = ?";
                presta = con.prepareStatement(qeury);
                presta.setString(1,ListUsers.getSelectedValue());
                presta.execute();
                JOptionPane.showMessageDialog(this, "delete");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "selected User");
                }
                
            }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(this, e.getMessage());
           }
    }//GEN-LAST:event_DeleteUserActionPerformed
public void chargeDataList()
{
     try
        {
             String qeury = "select * from [DB_MEMIOR].[dbo].[users] where IdUser > 1 ";
           
                            presta = con.prepareStatement(qeury);
                           // presta.setString(1,nameM.getText());
                            reset = presta.executeQuery();
                            
        Vector<String> temp = new Vector<String>();
        while (reset.next())
        {
            temp.add(reset.getString("username"));
        }
        //Jlist acctList = new Jlist(temp);
        ListUsers.setListData(temp);
        JOptionPane.showMessageDialog(this, "show data");
        }
        catch(SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JList<String> ListUsers;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
